### ISSUE TITLE
QGISを用いて地図をグローバル座標にマッピングする．

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/create-map-with-landmark#10]
屋外走行で得たデータを用いてQGIS上でグローバル座標にマッピングする．

**Comment by atsushi10mino** [comment]
ジオリファレンスを行う
![screenshot from 2018-09-23 20-39-44](https://user-images.githubusercontent.com/28559070/45927649-39fea700-bf71-11e8-937f-be05d1490c8c.png)
行った結果
![screenshot from 2018-09-23 20-44-48](https://user-images.githubusercontent.com/28559070/45927680-a679a600-bf71-11e8-98b0-34d6579a34c4.png)

重ね合わせた結果
![landmark_plus_map](https://user-images.githubusercontent.com/28559070/45927734-9ca47280-bf72-11e8-803d-8aa71c6199b1.png)

![landmark_plus_google](https://user-images.githubusercontent.com/28559070/45927727-53ecb980-bf72-11e8-9304-b9e01d0b5b09.png)

**Comment by yasuohayashibara** [comment]
お疲れさまです．
だいたい合っていますね．
少々左下になっている気もしますが，これは補正用のデータをつくばの基地局からもらっている影響でしょうか．

**Comment by atsushi10mino** [comment]
open street mapで１２点GNSS情報を使用しジオリファレンスしたもの
![12tengis](https://user-images.githubusercontent.com/28559070/46142426-e1d9e480-c291-11e8-949a-5c7d0f3f027d.png)

open street mapで最もエラー値が低い３点GNSS情報を使用しジオリファレンスしたもの
![3tengis](https://user-images.githubusercontent.com/28559070/46142403-cff84180-c291-11e8-8c59-00660c471649.png)

比較
![hikakugis12_3](https://user-images.githubusercontent.com/28559070/46142444-f74f0e80-c291-11e8-8a19-72ca109703bf.png)

３店でジオリファレンスした地図
![openmap](https://user-images.githubusercontent.com/28559070/46142538-46953f00-c292-11e8-9e22-eaff4eba5dff.png)

**Comment by yasuohayashibara** [comment]
こちらマッピングできましたので，issueを閉じます．
精度を上げる必要がある場合は別issueで議論しましょう．
