### ISSUE TITLE
リミットスイッチの状態をパブリッシュするノードを調査する

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/create-map-with-landmark#2]
リミットスイッチの状態をパブリッシュするノードの調査

**Comment by yasuohayashibara** [comment]
リミットスイッチの状態をパブリッシュするノードは無さそうなので，自分で製作することが必要かもしれない．

近いのはLegoのTouchセンサ？
http://wiki.ros.org/nxt_ros#Touch_Sensor

**Comment by atsushi10mino** [comment]
RapberryPIのI/Oを読んで，メッセージを流すノード
https://github.com/KazuyaHamaguchi/switch_test

**Comment by yasuohayashibara** [comment]
自分たちで開発しなくてはならなさそう．

**Comment by yasuohayashibara** [comment]
#4 にissueを引き継ぎ，こちらのissueは閉じます．
