### ISSUE TITLE
リミットスイッチの状態をパブリッシュするノードの開発

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/create-map-with-landmark#4]
リミットスイッチの状態をパブリッシュするノードを開発する．

**Comment by yasuohayashibara** [comment]
こちらが参考になる？
https://github.com/KazuyaHamaguchi/switch_test

**Comment by atsushi10mino** [comment]
https://github.com/KazuyaHamaguchi/switch_test
の動作を確認したのでこれを元に開発する

**Comment by atsushi10mino** [comment]
以下のコミットでスイッチの状態をパブリッシュするノードを開発した
[d3c8110f28ca5ef6e253e9cf7dc9a9b17d4abbfd](https://github.com/open-rdc/create-map-with-landmark/commit/d3c8110f28ca5ef6e253e9cf7dc9a9b17d4abbfd)

**Comment by atsushi10mino** [comment]
確認したのでissueを閉じます

**Comment by yasuohayashibara** [comment]
お疲れ様です．

以下ヘッダファイルなど依存関係があると思われますので，できればREADMEにInstallの方法などを書いたほうが良いと思います．
pigpiod_if2.h

以下のInstallなどを参考にすると良いと思います．
https://github.com/open-rdc/orne_navigation

あと，基本的にはネットワーク越しにスイッチのON/OFFを記録することになりますので，そちらの検証も必要ですね．
