### ISSUE TITLE
地図の作成

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/create-map-with-landmark#6]
#5 で決定したフレームワークを用いて地図を作成する．

**Comment by yasuohayashibara** [comment]
#7 のデータを用いて検証する．

**Comment by yasuohayashibara** [comment]
通常のgmapping
https://youtu.be/wOBqgdXa3X0

重みをすべて0としたときのgmapping
https://youtu.be/E_TUQOWb598
※正確でない地図が作成される．

**Comment by atsushi10mino** [comment]
反射強度を正規化し,上位10%のみの点をパブリッシュするノードの開発（ある一定以上の反射強度の点がある場合のみ）https://github.com/atsushi10mino/Intensity_test

**Comment by atsushi10mino** [comment]
とりあえず実験を行った
ポール3本を設置し周囲を走行ポールを移動を繰り返す
実験場所:2号館と4号館間から2号館とfuroの間あたりまで
時間:大体30分位
機体:β
![img_4850](https://user-images.githubusercontent.com/28559070/44031539-46464664-9f3f-11e8-9c9e-60f8d88f0316.JPG)

測位結果はfix解に収束するときもあった

サイズが大きくアップロードできないのでdavのusr/minoにあげた

**Comment by atsushi10mino** [comment]
[normalmap.zip](https://github.com/open-rdc/create-map-with-landmark/files/2395624/normalmap.zip)
通常のgmappingで生成した地図

**Comment by atsushi10mino** [comment]
従来の手法で作成した地図

![screenshot from 2018-09-19 14-59-37](https://user-images.githubusercontent.com/28559070/45733700-abaabe00-bc1c-11e8-97fa-8613e1a192f1.png)

**Comment by atsushi10mino** [comment]
https://drive.google.com/open?id=1sEK41usNWje9xBfDJ0mgaVKCF9S9rE_0
ランドマーク有りのbag

**Comment by atsushi10mino** [comment]
https://drive.google.com/open?id=1dNj_g_Aa-1g2mCN8Z2VYFVmNbBcSj1ba
ランドマーク無しのbag

**Comment by atsushi10mino** [comment]
データを確認したところ何故かオドメトリのtopicが出ていない
cmd_ velとimuのデータは取れている

**Comment by atsushi10mino** [comment]
取り直したデータ（ランドマーク有り）
https://drive.google.com/open?id=1WT0Iq5yZiLbn9l2MgaMaOT4ChL1P_3AU
ランドマーク無し
https://drive.google.com/open?id=1tiB0EsYGGHLJOCdVyWCtaT6Q6AJkbDwQ

**Comment by atsushi10mino** [comment]
gmappingで生成した地図
ランドマーク有り
![screenshot from 2018-09-22 21-48-45](https://user-images.githubusercontent.com/28559070/45917409-736fdd80-beb1-11e8-8e8f-73100b550046.png)
ランドマーク無し
![screenshot from 2018-09-22 21-49-15](https://user-images.githubusercontent.com/28559070/45917413-808ccc80-beb1-11e8-9f3c-2d5f53213a77.png)

**Comment by atsushi10mino** [comment]
scanデータが傾いている
機体のIMUが傾いている可能性

![rviz_screenshot_2018_09_22-21_55_11](https://user-images.githubusercontent.com/28559070/45917460-a49cdd80-beb2-11e8-9947-4263566541ba.png)

**Comment by atsushi10mino** [comment]
原因追究のためにもう一度地図生成したところ先ほどとは違う地図が生成された（ランドマーク有り）

![screenshot from 2018-09-22 22-07-01](https://user-images.githubusercontent.com/28559070/45917519-e37f6300-beb3-11e8-902b-b24a12e6f8bc.png)

**Comment by yasuohayashibara** [comment]
そういえば，gmappingはMCLを使用しているので，毎回異なるのは当然でした．ランダムに正規分布させたパーティクルにより自己位置推定するので，乱数の具合で地図が変わりますね．
（それだけ不安定な要因が含まれているということですね．）

**Comment by yasuohayashibara** [comment]
ランドマーク有でgmappingで地図を生成しました．
https://youtu.be/4iisqSt_rYo

いきなり角度が変わりますね．

比較として，rosbagを1/10で再生した地図も紹介します．
https://youtu.be/jkyltQa8-xo
一例ですが素晴らしく精度が上がりました．

**Comment by yasuohayashibara** [comment]
レーザが傾いて飛ぶ問題ですが，こちらを利用してIMUの値を変更することが可能だと思います．
http://wiki.ros.org/rosbag/Cookbook

おそらくは，
/imu_dataの
orientation:
x: 0　y: 0　z: -1　w:そのまま
とすると，水平にレーザが飛んでくれるようになると思います．

**Comment by atsushi10mino** [comment]
orientationを修正したが傾きは変わらなかった
rqt_graphを見るにtf_staticを修正する必要がありそう
![rosgraph](https://user-images.githubusercontent.com/28559070/45924674-01df7000-bf41-11e8-9cf1-b5cf248c1f03.png)
と思ったが起動し直したらrqt_graphのtopicがscanに変わっている
？？

**Comment by atsushi10mino** [comment]
odom座標系からみたデータ
![rviz_screenshot_2018_09_23-15_11_11](https://user-images.githubusercontent.com/28559070/45924779-22102e80-bf43-11e8-99aa-a3cd50f5e836.png)


base_linkみたデータ
![rviz_screenshot_2018_09_23-15_11_45](https://user-images.githubusercontent.com/28559070/45924780-263c4c00-bf43-11e8-870a-99754bbe5871.png)

**Comment by atsushi10mino** [comment]
３度目の正直ランドマーク有りbagファイル
https://drive.google.com/open?id=1sRSxvJDW2cUUNGjufRU7OT_mOOKaOZjC

生成された地図

![landmark_kaiten](https://user-images.githubusercontent.com/28559070/45925961-e8e2b900-bf58-11e8-9cb8-49e863555b12.png)

**Comment by yasuohayashibara** [comment]
スタートとゴールの位置のズレは？

**Comment by yasuohayashibara** [comment]
3度目に取り直したデータを使用してgmappingで地図を描いた様子
https://www.youtube.com/edit?o=U&video_id=vwEoD99-E-I

マシンが非力なせいだと思うが，まともに地図生成できない．
特に途中で一気に位置が飛ぶことがあり，もしかしたらバグがあるのかもしれない．

**Comment by atsushi10mino** [comment]
スタートとゴールのズレ
![rviz_screenshot_2018_09_23-17_28_29](https://user-images.githubusercontent.com/28559070/45927776-3d932d80-bf73-11e8-892e-481cb4b2b035.png)
少し引いた画像
![rviz_screenshot_2018_09_23-17_28_44](https://user-images.githubusercontent.com/28559070/45927778-4a178600-bf73-11e8-8152-e9771452790b.png)

スタート時はオドメトリ座標系とマップ座標系は一致していたがゴール時にはズレていた
スタート地点はマップ座標系だと思われるので
ズレは3.2mくらい？

**Comment by yasuohayashibara** [comment]
美濃君が開発した反射強度が高い点だけ抽出するノードでデータをチェックした．
https://github.com/atsushi10mino/Intensity_test

自転車の反射板の影響が大きく出ており，ランドマークを特定することが難しい
rvizで表示した様子
https://youtu.be/RAWfYLjskW8

ちなみに，別の興味で作成したものであるが，単純なしきい値(8000)を用いて抽出した結果
https://youtu.be/01D0vZWfoJw

対策できなければ，データの撮り直しをしなければならないかもしれない．

**Comment by yasuohayashibara** [comment]
比較的簡単な方法を思いついた
参考
http://wiki.ros.org/gmapping

１）rosbagのレーザレンジセンサデータの内，反射強度の高いものだけ抽出する．
２）それを用いてgmappingで自己位置推定
　　gmappingのパラメータを調整する必要があるかもしれない．
３）map → odomのtfを記録
４）オリジナルのrosbag内のodomのtfをこちらに入れ替える．
　　これはちょっとむずかしい？
５）再度入れ替えたrosbagでgmappingで自己位置推定
　　この時，ロボットのオドメトリの共分散を0にする

**Comment by atsushi10mino** [comment]
反射強度の高い点のみでgmappingを行った（パラメータ調整なし）
https://www.youtube.com/watch?v=2t-0O7B71Bs&t=1s
一応生成された地図
![strong_point_map](https://user-images.githubusercontent.com/28559070/46053444-d6959480-c17d-11e8-96f0-76676b3b184a.png)

**Comment by atsushi10mino** [comment]
オドメトリエラーをそれぞれ1/100した動画
2回試して思ったが反射強度の距離減衰と強度の正規化は相性が悪い

https://www.youtube.com/watch?v=EHinYs7bsIk&feature=youtu.be

**Comment by yasuohayashibara** [comment]
なるほどなかなかうまくいきませんね．
試してみたいgmappingのパラメータがありますので，使用したプログラムをいただければと思います．

**Comment by atsushi10mino** [comment]
変更箇所
![screenshot from 2018-09-26 16-10-12](https://user-images.githubusercontent.com/28559070/46063171-fb523200-c1a6-11e8-894a-e251c2b2fa96.png)
gmappingのlaunchにscan_intensityを追加
![screenshot from 2018-09-26 16-09-46](https://user-images.githubusercontent.com/28559070/46063152-ed041600-c1a6-11e8-95de-554edbacce45.png)
slam_gmapping.cppのサブスクライバをscanからstrong_reflection_pointに変更
![screenshot from 2018-09-26 16-11-00](https://user-images.githubusercontent.com/28559070/46063174-fd1bf580-c1a6-11e8-954a-3a1175037a26.png)
scan_intensityの抽出条件の緩和
![screenshot from 2018-09-26 16-11-10](https://user-images.githubusercontent.com/28559070/46063181-ff7e4f80-c1a6-11e8-83ed-900f9b75b24b.png)
topic名の修正

**Comment by atsushi10mino** [comment]
誤差２mになったときの動画
https://www.youtube.com/watch?v=1iLUd1LWePE&feature=youtu.be
bag:https://drive.google.com/open?id=1FU8W6Zh2xCrv8ZySgZMAWQSsDHZNaxum
param変更箇所
param name="iterations" value="10"
param name="srr" value="0.001"
param name="srt" value="0.002"
param name="str" value="0.001"
param name="stt" value="0.002"
param name="angularUpdate" value="1.571"

**Comment by atsushi10mino** [comment]
bagからtfをcsv形式で取り出し
map→odom座標系でみたデータ
https://drive.google.com/open?id=17HD7_8Who0hOhUVyO3JxcfWNcyvjxN6ehttps://drive.google.com/open?id=17HD7_8Who0hOhUVyO3JxcfWNcyvjxN6e
![map_odom](https://user-images.githubusercontent.com/28559070/46067522-fb0b6400-c1b1-11e8-99a9-cd2503671bd6.png)

**Comment by atsushi10mino** [comment]
rosbagのmerge
https://github.com/saurabverma/rosbag_filter_merge
使用方法
rosbag_merge.py output.bag input.bag input.bag

**Comment by atsushi10mino** [comment]
合成したbagファイル
元bagからtfを削除,反射強度の高い点のみで地図生成を行ったbagからtfのみ抽出し合成
https://drive.google.com/open?id=1z04eD78hPFRnoA6aEsNOTsEViaGU7KBX
自分の環境ではhokuyo_linkが読み込まれたり読み込まれなかったりする
tf_staticトピックbagファイルを再生したタイミングで配信はされているので読み込まれるはずなのに

また、変更点をすべて戻したがgmapping~.launchでの地図生成が何故かできない（合成前のbagでも）

**Comment by atsushi10mino** [comment]
launchのremap scan base_scanを消したら動いた謎
合成したbagでオドメトリエラーを0にし地図を生成したところ
hokuyo_linkが読み込まれていないが何故かできた
![merge_odom_map](https://user-images.githubusercontent.com/28559070/46079311-c0b1bf00-c1d1-11e8-9d17-6c61653d26d9.png)
綺麗
![rviz_screenshot_2018_09_26-21_16_04](https://user-images.githubusercontent.com/28559070/46079321-ceffdb00-c1d1-11e8-9586-0ac2503a3364.png)
差

**Comment by yasuohayashibara** [comment]
パラメータチューニングを行っているが，話が長くなりそうなので， #12 で議論する．

**Comment by atsushi10mino** [comment]
念のためもう一度行ったところ
先ほどとは違う位置に収束した
![merge_odom_map2](https://user-images.githubusercontent.com/28559070/46080474-fd32ea00-c1d4-11e8-9fee-75035b2875eb.png)
![rviz_screenshot_2018_09_26-21_39_38](https://user-images.githubusercontent.com/28559070/46080491-08861580-c1d5-11e8-949e-c05f571cf8e5.png)
オドメトリエラーを０にしても完全にオドメトリの経路を進んでいるわけではなさそう

**Comment by yasuohayashibara** [comment]
以下のパラメータを0にしてもmapフレームとodomフレームがずれる．
他にパラメータがないか探す．

```
      <param name="srr" value="0.1"/>
      <param name="srt" value="0.2"/>
      <param name="str" value="0.1"/>
      <param name="stt" value="0.2"/>
```

以下のように設定することで，mapとodomがずれない地図を書くことができる．
```
    <param name="lskip" value="1000000"/>
```

これでレーザを地図描画にのみ利用して，自己位置推定には使用しないようにできる．

**Comment by atsushi10mino** [comment]
以下の設定で実験データのrosbagを再生しgmappingを行いrosbagを記録
```
<launch>
    <param name="use_sim_time" value="true"/>
    <node pkg="gmapping" type="slam_gmapping" name="slam_gmapping" output="screen">
      <remap from="scan" to="strong_reflction_point"/>
      <param name="map_update_interval" value="5.0"/>
      <param name="lstep" value="0.01"/>
      <param name="astep" value="0.01"/>
      <param name="iterations" value="5"/>
      <param name="lsigma" value="0.05"/>
      <param name="srr" value="0.000001"/>
      <param name="srt" value="0.000002"/>
      <param name="str" value="0.000001"/>
      <param name="stt" value="0.000002"/>
      <param name="linearUpdate" value="0.1"/>
      <param name="angularUpdate" value="0.1"/>
    </node>
</launch>
```
記録したrosbagからtfのみを抽出，もとの実験データのrosbagと合成
記録したrosbag:https://drive.google.com/open?id=14CsT7FCnIYlamU7b0vrWAP4m5ZADIv3f
抽出後:https://drive.google.com/open?id=1l2UVb1eAwqShR9qfhmUguv8tRE_NRKUr
合成後:https://drive.google.com/open?id=1ImKsOlCi7uCKFEfvfoHl0GYgo-CFIXkR

合成後のbagで地図を生成する
その際https://github.com/open-rdc/create-map-with-landmark/issues/6#issuecomment-424712202
で行う
動画(途中から):https://youtu.be/FVC_y9x2IUk
今回はhokuyo_linkがちゃんと読み込まれている
生成された地図
![merge_tf_adjust](https://user-images.githubusercontent.com/28559070/46092504-f82f6400-c1ef-11e8-908e-21cee81be222.png)

３回実験を繰り返した際の終了時の姿勢
![rviz_screenshot_2018_09_26-23_59_40](https://user-images.githubusercontent.com/28559070/46091672-4479a480-c1ee-11e8-9a1e-dac49bcdc0bb.png)
![rviz_screenshot_2018_09_27-00_20_42](https://user-images.githubusercontent.com/28559070/46091680-46dbfe80-c1ee-11e8-9b73-efb06ae5d24a.png)
![rviz_screenshot_2018_09_27-00_30_20](https://user-images.githubusercontent.com/28559070/46091695-4ba0b280-c1ee-11e8-945c-2b41accad2df.png)
３回ともほぼ同じ位置であることがわかる

**Comment by yasuohayashibara** [comment]
少々予稿集の変更が必要となりますが，これで必要な実験データはすべて揃ったという認識で良いでしょうか？
そうであるなら予稿集の添削に入ります．

**Comment by atsushi10mino** [comment]
この地図を利用した自律移動を行って実験は完了となります

**Comment by yasuohayashibara** [comment]
なるほど自律移動も入っていたのですね．
もう一度予稿集（案）を読み直します．

**Comment by yasuohayashibara** [comment]
結果的に想定したフレームワークではなくなったが，地図を生成することができた．
長くなったので，次に議論するときには別issueにすることにして，issueを閉じます．
