### ISSUE TITLE
反射強度を含むrosbugを取得する

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/create-map-with-landmark#7]
地図を作成するために，ポールを置いた環境で，反射強度を含むrosbugを取得する．

**Comment by atsushi10mino** [comment]
[2018-05-30-13-26-03.bag.zip](https://github.com/open-rdc/create-map-with-landmark/files/2052414/2018-05-30-13-26-03.bag.zip)
反射強度を含んだbagファイル

**Comment by yasuohayashibara** [comment]
こちらrosbagの取得ができたのでissueを閉じます．

**Comment by yasuohayashibara** [comment]
gmappingで地図を生成している様子
https://youtu.be/ZwQVlOYhVFA
